version: '3.8'

services:
  api-server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysql
      - DB_NAME=SUBS_STAGING
      - DB_USER=root
      - DB_PASSWORD=12345678
      - API_KEY_1=sub_analytics_mhHT-jo1FcowxIKbqf3hAAMyUrRHKODxXhcd_PCHT5k
      - API_KEY_2=sub_analytics_HCO6tR59dEfXLmvy-OW9FRq_S1ud80LoretLJ-lDKk8
    depends_on:
      - mysql
    restart: unless-stopped

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=SUBS_STAGING
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped

volumes:
  mysql_data: